from yacs.config import CfgNode

_BASE_ZSL = CfgNode()
_BASE_ZSL.N_BLOCKS = 4
_BASE_ZSL.START_OUT_CHN = 8
_BASE_ZSL.CHN_SCALE_COEF = 2
_BASE_ZSL.VECTOR_SIZE = 200

_SEG_RCNN = CfgNode()
_SEG_RCNN.ENCODER = 'mobilenet'
_SEG_RCNN.DECODER_CHANNELS = [512, 320, 128, 64, 32]
_SEG_RCNN.VECTOR_SIZE = _SEG_RCNN.DECODER_CHANNELS[-1]

_TOPDOWN_RCNN = CfgNode()
_TOPDOWN_RCNN.VECTOR_SIZE = 256
_TOPDOWN_RCNN.EXTENDED_TWOMLP = False
_TOPDOWN_RCNN.EXTENDED_EMB_HEAD = False
_TOPDOWN_RCNN.BBOX = CfgNode()
_TOPDOWN_RCNN.BBOX.SCORE_THRSH = 0.5
_TOPDOWN_RCNN.BBOX.NMS_THRSH = 0.5
_TOPDOWN_RCNN.BBOX.DET_PER_IMH = 60
_TOPDOWN_RCNN.BBOX.FG_IOU_THRSH = 0.5
_TOPDOWN_RCNN.BBOX.BG_IOU_THRSH = 0.5
_TOPDOWN_RCNN.BBOX.BS_PER_IMG = 512
_TOPDOWN_RCNN.BBOX.POS_FRAQ = 0.25
_TOPDOWN_RCNN.BBOX.REG_W = None
_TOPDOWN_RCNN.BBOX.REPR_SIZE = 1024

MODEL_DEFAULTS = {'base_model': _BASE_ZSL, 'seg_rcnn': _SEG_RCNN, 'topdown_rcnn': _TOPDOWN_RCNN}
