from yacs.config import CfgNode


_TRANSFORMATIONS = CfgNode()
_TRANSFORMATIONS.NORMALIZE = False
_TRANSFORMATIONS.INTERPOLATION = 3
_TRANSFORMATIONS.RANDOM_ERAZING = CfgNode()
_TRANSFORMATIONS.RANDOM_ERAZING.FLAG = 0.
_TRANSFORMATIONS.RANDOM_ERAZING.MAX_AREA = 0.1
_TRANSFORMATIONS.RANDOM_ERAZING.MIN_RATIO = 0.3
_TRANSFORMATIONS.COLOR = CfgNode()
_TRANSFORMATIONS.COLOR.BRIGHTNESS = (0.7, 1.2)
_TRANSFORMATIONS.COLOR.CONTRAST = (0.7, 1.2)
_TRANSFORMATIONS.COLOR.SATURATION = (0.7, 1.2)
_TRANSFORMATIONS.COLOR.HUE = (-0.1, 0.1)

TRANSFORMATION_DEFAULTS = {'v1_transforms': _TRANSFORMATIONS}
